### ISSUE TITLE
Add Windows 10 support

### ISSUE THREAD

**Issue by anthonyhenderson** [jcheng31/ForecastPCL#10]
First off, thanks for creating this library! Super useful.

When I upgraded my Windows 8.1 app to a Windows 10 universal app I got the following error when trying to add your NuGet package:

Not compatible with UAP,Version=v10.0 (win10-x64-aot)

**Comment by jcheng31** [comment]
Hey, glad you're finding it useful :)
I'll take a look at this in a bit.

**Comment by jcheng31** [comment]
It _seems_ the code itself is fine (i.e. it doesn't reference anything that can't be used in a Universal App), though the way I have the NuGet package set up is wrong. I'll fix this when I can, though I'm a bit busy right now so it might take a week or so. Sorry about that :(

In the meantime, a workaround would be to clone the project, building it, then adding a reference to the .dll directly - that should (I think) work. It does mean stepping outside the NuGet loop, though.

**Comment by anthonyhenderson** [comment]
Yea I figured I was simply a packaging issue but I wasn't familiar enough with NuGet to know where to start. No rush, I might try your workaround just to see if it works in general. Thanks!

**Comment by jcheng31** [comment]
Alright, I've uploaded version 2.2 to NuGet, which should be packaged properly now (and also contains additional language support - see #9). Let me know if it works for you :)

**Comment by anthonyhenderson** [comment]
@jcheng31 Works perfectly. Thanks for the quick turnaround!

**Comment by anthonyhenderson** [comment]
Hey, so it looks like this works when building a Debug package but not when building a Release package in Visual Studio. I'm getting some compiler warnings:

    warning : Assembly 'Microsoft.Threading.Tasks.Extensions' requests the address of the virtual method 'Stream.BeginRead(byte[], int, int, AsyncCallback, object)' which is not available in the targeted .NET platform. Please ask the author of 'Microsoft.Threading.Tasks.Extensions' to provide an implementation that can be used in the currently targeted .NET platform.
    warning : Assembly 'Microsoft.Threading.Tasks.Extensions' requests the address of the virtual method 'Stream.EndRead(IAsyncResult)' ...
    warning : Assembly 'Microsoft.Threading.Tasks.Extensions' requests the address of the virtual method 'Stream.BeginWrite(byte[], int, int, AsyncCallback, object)' ...
    warning : Assembly 'Microsoft.Threading.Tasks.Extensions' requests the address of the virtual method 'Stream.EndWrite(IAsyncResult)' ...

Since you didn't write that assembly, I'm assuming it's just not supported for .NET native compilation for some reason. This is causing ForecastPCL not to be included in the final store packages that VS creates :(

My assumption here is that there's an extension method you're using that's causing this. I may try to fix this one myself and contribute for once but I wanted to share here in case something came to mind for you when you read these warnings :)

**Comment by jcheng31** [comment]
Hmm, that's unfortunate :| I'll try take a look soon, but I'm definitely open to contributions!

I _think_ that library is used as part of the async/await package I'm using for backwards compatibility - Microsoft.Bcl.Async - or one of its dependencies.

**Comment by jcheng31** [comment]
Come to think of it, that library might not be necessary any longer. It only adds support for async/await in .NET 4, WP 7.5, and Silverlight 4, but the PCL doesn't (off the top of my head) even target those now.

**Comment by microhenderson** [comment]
Ok yea I'll keep trying to get it working. When I tried to build my app directly against your project I was seeing entirely different issues. Are the references (Microsoft.Bcl* etc.) supposed to be NuGet packages or something else? In VS2015 they look like regular references (different icon next to them).

**Comment by anthonyhenderson** [comment]
Ok yea I'll keep trying to get it working. When I tried to build my app directly against your project I was seeing entirely different issues. Are the references (Microsoft.Bcl* etc.) supposed to be NuGet packages or something else? In VS2015 they look like regular references (different icon next to them).

**Comment by jcheng31** [comment]
Yeah, they're NuGet packages.

**Comment by anthonyhenderson** [comment]
So I've been trying to build my project by directly referencing your code and I'm hitting this error:

    2>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(791,7): warning : Method 'HttpClientHandler.set_AutomaticDecompression(DecompressionMethods)' was not included in compilation, but was referenced in method 'ForecastApi.GetCompressionHandler()'. There may have been a missing assembly.

Haven't figured it out yet but I thought I'd add the info here.

**Comment by anthonyhenderson** [comment]
Closing this issue as I've gotten closer to the root cause. Will open a more specific one.
