### ISSUE TITLE
Debug configuration test FAILED

### ISSUE THREAD

**Issue by bklabs** [jcheng31/ForecastPCL#12]
Hi - I've updated lib to version 2.3.0(Windows Phone Silverlight 8.1) and got a certification error in dev center:

Debug configuration test
FAILED
Debug configuration
•Error Found: The debug configuration test detected the following errors:◦The binary ForecastPCL.dll is built in debug mode.
•Impact if not fixed: Windows Phone Store doesn’t allow a debug version of an app.
•How to fix: Please make sure the app isn't linking to any debug versions of a framework and it is built with the release configuration with optimization enabled.

Best regards 
Dmitry Belov
BK Labs

**Comment by jcheng31** [comment]
Oops, thanks for this! Nuget was packaging the Debug version - I've just repackaged the Release .dll and uploaded it to the site as version 2.3.1. Let me know if that works!

**Comment by bklabs** [comment]
It works! Thank you.

**Comment by jcheng31** [comment]
No problem -  glad to help :)
